{{- if .Values.windows.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: hello-windows
  labels:
    {{- include "hello.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows
spec:
  type: ClusterIP
  selector:
    app: hello-windows
  ports:
    - port: {{ .Values.windows.port }}
      targetPort: {{ .Values.windows.port }}
      protocol: TCP
      name: http
{{- end }}
